### ISSUE TITLE
get_orders() return empty

### ISSUE THREAD

**Issue by GozdeKorpe** [binance/binance-futures-connector-python#100]
I am trying to get all my open orders but it doesn't work.
code:
import logging
from binance.um_futures import UMFutures
from binance.lib.utils import config_logging
from binance.error import ClientError
import keys

config_logging(logging, logging.DEBUG)

api_key = keys.API_KEY
secret_key = keys.SECRET_KEY

client = UMFutures(key=api_key, secret=secret_key)

response = client.get_orders()
logging.info(response)

**Comment by 2pd** [comment]
Please refer to this example file, https://github.com/binance/binance-futures-connector-python/blob/main/examples/cm_futures/trade/get_order.py

symbol is required for this method.

thanks

**Comment by GozdeKorpe** [comment]
> Please refer to this example file, https://github.com/binance/binance-futures-connector-python/blob/main/examples/cm_futures/trade/get_order.py
> 
> symbol is required for this method.
> 
> thanks
