### ISSUE TITLE
get_orders only returns one open order

### ISSUE THREAD

**Issue by GozdeKorpe** [binance/binance-futures-connector-python#102]
I am using : def get_orders(self, **kwargs):
    """
    |
    | **Current All Open Orders (USER_DATA)**
    | *Get all open orders on a symbol. Careful when accessing this with no symbol.*
    | *If the symbol is not sent, orders for all symbols will be returned in an array.*
This function in umfutures it should give all open orders as a list because ı am not using a symbol but it only returns one open order.

**Comment by aisling-2** [comment]
@GozdeKorpe Can you share the used package version and :
- provide a example code using the `get_orders()`;
- expected response and what you get instead;
- if on binance.com website you do indeed have several open orders;

The above will help us to understand your context more and investigate better.
