### ISSUE TITLE
how set up proxies and how to use it, can you give me examples.

### ISSUE THREAD

**Issue by ncgege** [binance/binance-futures-connector-python#104]
from binance.cm_futures import CMFutures
proxies = { 'https': 'http://1.2.3.4:8080' }
client= CMFutures(proxies=proxies)
if i have a server ,how to set it ,that i can use proxies?
becuase my compute can visit fapi.binance.com but my server can do it.
so i wanna using proxy.
Can you tell me more details ,thanks.

**Comment by aisling-2** [comment]
@ncgege Apologies, but the guidance on how one can setup a proxy is beyond this project's scope, you need to investigate that by yourself.
