### ISSUE TITLE
what to add to the requirements file?

### ISSUE THREAD

**Issue by gezabohus** [binance/binance-futures-connector-python#106]
Hi,

It doesn't seem like a good idea to use a different name for the project and what you need to import. 

What do I write in my requirements file?
binance_future_connector==3.3.1

If so, automatic requirements generation fails. (I'm trying to use pipreqs.) It finds "import binance" and looks for that module and there is one: https://pypi.org/project/binance.py/ which is unrelated to this one.

Thanks,

Geza

**Comment by 2pd** [comment]
Try this

`binance-futures-connector==4.0.0` or `binance-futures-connector==4.0.0rc3` if you like to try the rc versions.

Please let us know if it works.

Thanks

**Comment by gezabohus** [comment]
Thanks 2pd, but that was not the issue. I can edit the requirements file by hand as you suggest, but since one needs to import binance as opposed to binance-future-connector, automatic requirement generation fails.

**Comment by 2pd** [comment]
In the latest release, we think its stable enough to remove rc from version.  Now you can install it by 

`pip install binance-futures-connector` to get latest update.
