### ISSUE TITLE
Allow separate callbacks for market data and user data stream

### ISSUE THREAD

**Issue by rahulpoptani** [binance/binance-futures-connector-python#107]
v3.3.1 Allows us to specify separate callbacks for market and user data. This would help to manage both types of messages separately.
```
websocketClient.instant_subscribe(stream=instruments, callback=marketDataMethod)
websocketClient.user_data(listen_key=client.new_listen_key()['listenKey'], id=1, callback=userDataMethod)
```

v4.0.0rc1 We have to specify callback methods at initialization level. With this implementation for each message received, 1 additional CPU cycle will be required just for the filtering between different types of messages.
```
websocketClient = UMFuturesWebsocketClient(on_message=marketDataMethod)
websocketClient.subscribe(stream=['btcusdt@kline_1m', 'ethusdt@kline_1m'])
websocketClient.user_data(listen_key=client.new_listen_key()['listenKey'],id=1) 
```

**Comment by 2pd** [comment]
Thanks for the feedback.  

In v3, each method will create a new socket connection, which make it possible to hook callback for each connection.
From v4, we only maintain only one connection, which is easy to maintain and reduce the potential problem.

There are 2 solutions:
- Multi websocket clients;  You could attach different call back to each client.
- Handle event logic behind the `on_message` call back.  Websocket messages has the event type, which can be used to identify for different process.
