### ISSUE TITLE
binance-futures-connector-python conflicts with binance-connector-python

### ISSUE THREAD

**Issue by saituxg** [binance/binance-futures-connector-python#111]
Websocket on binance-futures-connector-python conflicts with binance-connector-python (overwrite files)
example :
CMFuturesWebsocketClient().start() 
works if you install binance-futures-connector-python after binance-connector-python if not you get "'CMFuturesWebsocketClient' object has no attribute 'start' "

**Comment by 2pd** [comment]
Please download the latest version from both connectors, they should works together.
