### ISSUE TITLE
timout reconnecting websocket in testnet area

### ISSUE THREAD

**Issue by Bandita88** [binance/binance-futures-connector-python#112]
WebSocket connection established.
WebSocket receive timeout. Reconnecting...

using my strategy for future for market depth,  perpetual i always receive this error. 
how can i resolve? 

async def connect_to_websocket():
    uri = 'wss://testnet.binance.vision/ws/btcusdt_perp@depth'
    
    async with websockets.connect(uri) as ws:
        print("WebSocket connection established.")

        while True:
            try:
                message = await asyncio.wait_for(ws.recv(), timeout=60)  # Imposta un timeout per la ricezione dei messaggi
                await handle_message(message)
            except websockets.exceptions.ConnectionClosed:
                print("WebSocket connection closed. Reconnecting...")
                break
            except asyncio.TimeoutError:
                print("WebSocket receive timeout. Reconnecting...")
                break
            except Exception as e:
                print("An error occurred:", str(e))
                break

def run_event_loop():
    while True:
        try:
            loop = asyncio.get_event_loop()
            loop.run_until_complete(connect_to_websocket())
        except Exception as e:
            print("An error occurred:", str(e))
            break

if __name__ == '__main__':
    await connect_to_websocket()

**Comment by 2pd** [comment]
The url of `testnet.binance.vision` is for spot testnet, which doesn't has the symbol `btcusdt_perp`.

The futures testnet details can be found at:  https://binance-docs.github.io/apidocs/futures/en/#testnet
