### ISSUE TITLE
.ProxyError: HTTPSConnectionPool(host='fapi.binance.com', port=443)

### ISSUE THREAD

**Issue by huoshenmanbu** [binance/binance-futures-connector-python#114]
could you tell me how to solve this error？
My code :
response = um_futures_client.new_order_test(
            symbol="BTCUSDT",
            side="SELL",
            type="LIMIT",
            quantity=0.001,
            timeInForce="GTC",
            price=59808.02,
        )

occur error:

ProxyError
requests.exceptions.ProxyError: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/order/test?
(Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))))

Traceback (most recent call last)
The above exception was the direct cause of the following exception:
The above exception was the direct cause of the following exception:
File "E:\development\python\python38\lib\site-packages\requests\adapters.py", line 486, in send
resp = conn.urlopen(
File "E:\development\python\python38\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
retries = retries.increment(
File "E:\development\python\python38\lib\site-packages\urllib3\util\retry.py", line 515, in increment
raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]

**Comment by 2pd** [comment]
How do you create the `um_futures_client`, via any proxy?

**Comment by 2pd** [comment]
Please open new issue for another further concern. I'm sure it is caused by connection issue in the client side.
