### ISSUE TITLE
ModuleNotFoundError 4 import nest_asyncio       5 import aiohttp ----> 6 from binance.aio import AsyncClient       8 nest_asyncio.apply()      10 ModuleNotFoundError: No module named 'binance.aio'

### ISSUE THREAD

**Issue by Bandita88** [binance/binance-futures-connector-python#117]
hi everyone, 
i can go ahead with my strategy because i receive always the errore module not found error. 
i have try to insatall pip install python-binance
disinstall and reinstall
but always obteined the error. 
please help me. 

**---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[3], line 6
      4 import nest_asyncio
      5 import aiohttp
----> 6 from binance.aio import AsyncClient
      8 nest_asyncio.apply()**

ModuleNotFoundError: No module named 'binance.aio'

**Comment by 2pd** [comment]
Sorry I don't think the issue is from this library.
You are always welcome to open topic at dev.binance.vision for API related concern.

Thanks
