### ISSUE TITLE
How to use proxy in UMFuturesWebsocketClient()?

### ISSUE THREAD

**Issue by Tarryhao** [binance/binance-futures-connector-python#121]
proxie = {'https': 'http://127.0.0.1:7890'}
I am testing [websocket userdata](https://github.com/binance/binance-futures-connector-python/blob/main/examples/websocket/um_futures/user_data.py) and I can obtain the data using
 "client = UMFutures(api_key, proxies=proxie)
  response = client.new_listen_key()",
but the program executes until "ws_client = UMFuturesWebsocketClient(on_message=message_handler)"Will get stuck due to proxy issues. How can UMFuturesWebsocketClient use a proxy?

**Comment by urbanogt** [comment]
I'm having a look, will update with a proposal/code fix over the week for the connector.

**Comment by 2pd** [comment]
This is already supported in latest version
