### ISSUE TITLE
UMFuturesWebsocketClient error with on_message argument

### ISSUE THREAD

**Issue by someuser522** [binance/binance-futures-connector-python#122]
Hello to anyone who will read this!

as i take this example 1:1 https://github.com/binance/binance-futures-connector-python/blob/main/examples/websocket/um_futures/kline.py
got error “UMFuturesWebsocketClient.init() got an unexpected keyword argument ‘on_message’”
at same time on GIT arg on_message present! here it is.
https://github.com/binance/binance-futures-connector-python/blob/main/binance/websocket/um_futures/websocket_client.py#L22

pip ver. binance-futures-connector 3.3.1
can someone give me some hint please what is wrong & how to FIX?
PS. Issue looks like stable reproduced & confirmed also by Binance support representative

**Comment by 2pd** [comment]
Sorry for the confusing;  We have remove the rc from the latest release, it will work.
