### ISSUE TITLE
CLOSE frame received, closing websocket connection

### ISSUE THREAD

**Issue by Yang697** [binance/binance-futures-connector-python#124]
I subscribed to the ticker for all products at once, using the COMBINED method. But it raise a warning:CLOSE frame received, closing websocket connection. Is there a limit to the number of subscriptions?

**Comment by jerrylee2013** [comment]
I also has a similar question. I subscribe both ethusdt and btcusdt bookticker.  Then later I unsubscribe ethusdt and try to keep only btcusdt, but the result is that "CLOSE frame received, closing websocket connection".  How can I remove one of the symbol from the subscribe list?

**Comment by 2pd** [comment]
> I subscribed to the ticker for all products at once, using the COMBINED method. But it raise a warning:CLOSE frame received, closing websocket connection. Is there a limit to the number of subscriptions?


How many streams did you subscribe?

**Comment by 2pd** [comment]
> I also have a similar question. I subscribe both ethusdt and btcusdt bookticker. Then later I unsubscribe ethusdt and try to keep only btcusdt, but the result is that "CLOSE frame received, closing websocket connection". How can I remove one of the symbol from the subscribe list?


```json
{
    "method": "UNSUBSCRIBE",
    "params":
        [
            "btcusdt@depth"
        ],
     "id": 1
}

```

To unsubscribe, you can send the above message to the server.

**Comment by jerrylee2013** [comment]
I myself found the problem of my code.
According to the binance document, 
> WebSocket connections have a limit of 10 incoming messages per second.
the "list_subscribe" is sent too frequently, so the server broke the connection. 
I move the "list_subscribe" to a new thread and unsubscribe works well.

**Comment by 2pd** [comment]
Thanks for update.
