### ISSUE TITLE
V2 update breaking my code.

### ISSUE THREAD

**Issue by chigozieokoroafor** [binance/binance-futures-connector-python#128]
Was requested to update to V2 to get my balances but after doing so, couldn't create orders using the futures_creat_order method again. Currently trying to figure out how to do so.

**Comment by 2pd** [comment]
The library has to upgrade with better design or issue fixing.  It may has breaking change during major version upgrade, so it's suggested to have fully test with library when it has the major upgrade. For example , v1 -> v2,  v2 -> v3, etc.
