### ISSUE TITLE
Websocket arguments errors

### ISSUE THREAD

**Issue by gabriel-romero-poza** [binance/binance-futures-connector-python#129]
I'm new on this package and i'm still learning. Today I tried to use the websocket and copied and pasted the example files, but I always get the following errors:

[{
	"owner": "_generated_diagnostic_collection_name_#2",
	"code": {
		"value": "E1123:unexpected-keyword-arg",
		"target": {
			"$mid": 1,
			"external": "https://pylint.readthedocs.io/en/latest/user_guide/messages/error/unexpected-keyword-arg.html",
			"path": "/en/latest/user_guide/messages/error/unexpected-keyword-arg.html",
			"scheme": "https",
			"authority": "pylint.readthedocs.io"
		}
	},
	"severity": 8,
	"message": "Unexpected keyword argument 'on_message' in constructor call",
	"source": "Pylint",
	"startLineNumber": 13,
	"startColumn": 13,
	"endLineNumber": 13,
	"endColumn": 65
}]

[{
	"owner": "_generated_diagnostic_collection_name_#2",
	"code": {
		"value": "E1120:no-value-for-parameter",
		"target": {
			"$mid": 1,
			"path": "/en/latest/user_guide/messages/error/no-value-for-parameter.html",
			"scheme": "https",
			"authority": "pylint.readthedocs.io"
		}
	},
	"severity": 8,
	"message": "No value for argument 'callback' in method call",
	"source": "Pylint",
	"startLineNumber": 15,
	"startColumn": 1,
	"endLineNumber": 19,
	"endColumn": 2
}]

**Comment by 2pd** [comment]
Can you not copy and paste the example code, but just run the example directly and see if it works?
