### ISSUE TITLE
Support for mark price stream for all market

### ISSUE THREAD

**Issue by erolasan** [binance/binance-futures-connector-python#159]
Hi,

Can we add support for the WebSocket client to subscribe to the all-market stream for mark prices -
https://binance-docs.github.io/apidocs/futures/en/#mark-price-stream-for-all-market

It should be !markPrice@arr or !markPrice@arr@1s

Thanks

**Comment by alplabin** [comment]
It has been added in the [last release](https://github.com/binance/binance-futures-connector-python/releases/tag/v4.1.0)
