### ISSUE TITLE
502 bad gateway while order placement

### ISSUE THREAD

**Issue by suparn2304** [binance/binance-futures-connector-python#168]
06-02-24 07:29:15 ERROR: Handshake status 502 Bad Gateway -+-+- {'server': 'awselb/2.0', 'date': 'Tue, 06 Feb 2024 07:29:15 GMT', 'content-type': 'text/html', 'content-length': '122', 'connection': 'keep-alive'} -+-+- b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n</body>\r\n</html>\r\n' - goodbye binance api error

**Comment by aisling-2** [comment]
More context is needed.
Example: What did you run? What did you expect? What have you tried to fix? What version are you using.
If this is still occurring, feel fee to reopen this issue with the detail, so that we can try to replicate on our side.
