### ISSUE TITLE
Websocket connection exceptions are not handled by the user neither the on_error callback is called

### ISSUE THREAD

**Issue by malvanos** [binance/binance-futures-connector-python#173]
Websocket connection exceptions are not handled by the user neither the on_error callback is called. It seems that there is a pull request for that #158. However, I believe the pull request for the Spot is better: https://github.com/binance/binance-connector-python/pull/274 compared with #158.

Expected behaviour
Websocket connection errors should be handled by the on_error callback.

Actual behaviour
The exception is raised inside the thread managing the websocket connection.

Steps to reproduce
When closing the connection with any tool it will make the read to throw an exception.

**Comment by Drake1804** [comment]
Got the same issue

**Comment by xuanronaldo** [comment]
Good job, Dude. I don't understand why this PR hasn't been merged yet.

**Comment by alplabin** [comment]
This solution has been added in the [last release](https://github.com/binance/binance-futures-connector-python/releases/tag/v4.1.0).
