### ISSUE TITLE
## Description

### ISSUE THREAD

**Issue by Bukaram** [binance/binance-futures-connector-python#176]
## Description

Fix C++ includes broken at https://github.com/trustwallet/wallet-core/pull/3751

## Checklist

- [x] Create pull request as draft initially, unless its complete.
- [x] Add tests to cover changes as needed.
- [x] Update documentation as needed.
- [x] If there is a related Issue, mention it in the description.

If you're adding a new blockchain

- [x] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain.

_Originally posted by @satoshiotomakan in https://github.com/trustwallet/wallet-core/pull/3755_

_Originally posted by @Bukaram in https://github.com/Bukaram/Metamask/issues/1_

**Comment by MokshJain11** [comment]
Hi Binance team,

I would like to request access to the Binance Futures Testnet to test my trading strategies using the API.

Email: mokshkasliwal11@gmail.com  
GitHub Username: MokshJain11

Thank you!
