### ISSUE TITLE
install futures connector in IOS (ipad)

### ISSUE THREAD

**Issue by Benjuoli** [binance/binance-futures-connector-python#180]
Hello,

I have been working on a futures trading bot and it is working fine (regardless of the results). I would like to have the bot running on my ipad.

It seems like pythonista (Pyto) would be a good choice for it, but i cannot install the pip binance futures connector or the ta.

Is there a solution/alternative for it?

Thanks

**Comment by aisling-2** [comment]
Thank for your interest in our library, although I believe the not being able to install on iPad is beyond our control, we're only developing library, with no attachment to the type of devices it's run. 
Maybe this is related with the PyPI itself? Please seek help from their side.
