### ISSUE TITLE
futures account 

### ISSUE THREAD

**Issue by yardenyechiel** [binance/binance-futures-connector-python#185]
Hi , and thanks for your work here 
i am trying to get - client.futures_account()
and i respond - GET /fapi/v1/account is retired, please use GET /fapi/v2/account
i know it's a small issue , i can see that there are - FUTURES_API_VERSION = 'v1' and FUTURES_API_VERSION2 = "v2"
how do i change the function to call the FUTURES_API_VERSION2 = "v2" in your code ? 
thanks

**Comment by alplabin** [comment]
As said in the documentation, the endpoint `GET /fapi/v2/account` will soon be deprecated and replaced by the endpoint `GET /fapi/v3/account`. I therefore suggest you to use the new version, `GET /fapi/v3/account`, added in the [last release](https://github.com/binance/binance-futures-connector-python/releases/tag/v4.1.0).
