### ISSUE TITLE
/fundingInfo endpoint not supported

### ISSUE THREAD

**Issue by lautaromss** [binance/binance-futures-connector-python#188]
There is an endpoint on Binance's API, `GET /fapi/v1/fundingInfo`, which doesn't seem to be a function in the connector to use that endpoint.

The endpoint can be found in Binance docs: https://binance-docs.github.io/apidocs/futures/en/#get-funding-rate-info

You can retrieve data from that endpoint by simply going to: https://fapi.binance.com/fapi/v1/fundingInfo

**Comment by alplabin** [comment]
It has been added to the [latest release](https://github.com/binance/binance-futures-connector-python/releases/tag/v4.1.0)
