### ISSUE TITLE
continous kline don't support 1s interval?

### ISSUE THREAD

**Issue by Forward0908** [binance/binance-futures-connector-python#191]
how get 1s interval future kline?

**Comment by ds-academy** [comment]
available intervals for futures :
  1m
  3m
  5m
  15m
  30m
  1h
  2h
  4h
  6h
  8h
  12h
  1d
  3d
  1w
  1M

**Comment by Raseng92** [comment]
websockets , subscribe to kline updates and return at 1 s or less

**Comment by alplabin** [comment]
Unfortunately, the Kline/Candlestick chart intervals for the WebSocket Streams are similar to what @ds-academy previously covered. For more details, you can refer to the documentation below:
- [Kline/Candlestick Streams](https://developers.binance.com/docs/derivatives/usds-margined-futures/websocket-market-streams/Kline-Candlestick-Streams)
- [Kline/Candlestick chart intervals](https://developers.binance.com/docs/derivatives/usds-margined-futures/common-definition)
