### ISSUE TITLE
/futures/data/topLongShortAccountRatio api is missing

### ISSUE THREAD

**Issue by garryshield** [binance/binance-futures-connector-python#20]
[Top Trader Long/Short Ratio (Accounts)](https://binance-docs.github.io/apidocs/futures/en/#top-trader-long-short-ratio-accounts)

**Comment by andrea-c-binance** [comment]
@garryshield thanks for reporting this, we will try to add this soon.

**Comment by Basheer-alsyani** [comment]
29
