### ISSUE TITLE
"error.ReactorNotRestartable() twisted.internet.error.ReactorNotRestartable"- Binance websocket api

### ISSUE THREAD

**Issue by sagar23sharma** [binance/binance-futures-connector-python#25]
I am getting an issue with websocket. Any example I run from https://github.com/Binance-docs/binance-futures-connector-python/tree/main/examples/websocket/futures gives me the following error - "WARNING:root:WebSocket connection closed: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake), code: 1006, clean: False, reason: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)".

Whenever I try to rerun the examples I get the error "error.ReactorNotRestartable() twisted.internet.error.ReactorNotRestartable".

I have found out that I can escape this error by uninstalling and then reinstalling the twisted library. But then I have to repeat the reinstallment every time I want to start the websocket. Since this isn't a feasible solution. Can someone here help me with how to resolve this issue? What would be the most appropriate way to close the websocket connection since ws_client = FuturesWebsocketClient(), ws_client.stop()  is leading to this issue.

**Comment by PengdaLiu** [comment]
I encountered the same issue.

**Comment by andrea-c-binance** [comment]
thanks for reporting, we will take a look at this.

**Comment by 2pd** [comment]
can you share some info like, your os, python vesion etc.

**Comment by sagar23sharma** [comment]
Windows 11, Python 3.9.5, Twisted 22.4.0. Please let me know if you need anything else

**Comment by sagar23sharma** [comment]
I see that a similar issue exists in the spot api - https://github.com/binance/binance-connector-python/issues/114 . Any ETA to resolve this or any update?

**Comment by 2pd** [comment]
Please update to the latest version with new websocket design.
