### ISSUE TITLE
onClose callback

### ISSUE THREAD

**Issue by fyr233** [binance/binance-futures-connector-python#28]
```python
from binance.websocket.futures.websocket_client import FuturesWebsocketClient
ws_client = WebsocketClient()
ws_client.instant_subscribe(
    stream=['bnbusdt@bookTicker', 'ethusdt@bookTicker'],
    callback=message_handler,
)
```
websocket接口怎么做掉线重连？在哪里指定onClose回调函数？

How can I set an onCLose() callback function for FuturesWebsocketClient? 
I want to reconnect to the server when I loss the connect.

**Comment by smeana** [comment]
Hello, have you solved this issue?

**Comment by fyr233** [comment]
> Hello, have you solved this issue?

No, it seems to have some functions to deal with connection lost, but not customizable.

**Comment by Sharaddition** [comment]
You may use `is_alive()` with a loop to check if the connection is not closed.

```
while True:
        if ws_client.is_alive():
            time.sleep(1)
        else:
            print('WS closed')
            break
```

**Comment by 2pd** [comment]
Please update to the latest version, you will be able to pass call back method to `on_close` when init the websocket client.

`my_client = UMFuturesWebsocketClient(on_message=message_handler, on_close=on_close_method) `
