### ISSUE TITLE
ModuleNotFoundError: No module named 'binance.um_futures'

### ISSUE THREAD

**Issue by Stitry** [binance/binance-futures-connector-python#37]
Hi, 
I'm quite new here. 

I used to use "import binance.future"
I saw in the doc that it changed to 'binance.um_futures'.

I uninstalled package with 'pip uninstall binance-futures-connector'
Then i did a 'pip binance-futures-connector'

Since then i get the error ModuleNotFoundError: No module named 'binance.um_futures'
It works nice on my laptop, not at all on my second computer

Any ideas? thanks for help.

**Comment by 2pd** [comment]
To install, you should run:

`pip install binance-futures-connector`

to verify if you have the package installed:

` pip list | grep binance-futures-connector`

If there is no result, then the package is not properly installed. Please check the readme doc and make sure you can install the package.

**Comment by Rilin** [comment]
I'm facing the same problem .
getting same error : "ModuleNotFoundError: No module named 'binance'"
pip3.10 list | grep binance-futures-connector
binance-futures-connector 3.1.1

**Comment by 2pd** [comment]
We can't reproduce the error.

**Comment by sephriot** [comment]
Same thing happened to me today while using Python 3.10. After downgrading to 3.9 it works without any issues.
