### ISSUE TITLE
new order stop maket error

### ISSUE THREAD

**Issue by qiudaozhang** [binance/binance-futures-connector-python#41]
here is my code

```python
params = {
                "positionSide": "LONG",
                "stop_price": stop_price 
            }
# s eq BTCUSDT
self.client.new_order(symbol=s, side="SELL", type="STOP_MARKET",
                      **params)
```

error is 

1102, 'A mandatory parameter was not sent, was empty/null, or malformed.'

According to the API description, are not all the necessary parameters passed?

**Comment by qiudaozhang** [comment]
My mistake stop_price=> stopPrice

**Comment by Augustine-Charly** [comment]
Looks like the issue is self resolved, good job. Kindly close the issue.
