### ISSUE TITLE
duble logging

### ISSUE THREAD

**Issue by Rilin** [binance/binance-futures-connector-python#44]
i logging to some log in my script

```

console_out = logging.StreamHandler()
log_format = logging.Formatter(fmt='%(asctime)s.%(msecs)03d : [%(levelname)s] : %(message)s',datefmt='%Y.%m.%d %H:%M:%S')
console_out.setFormatter(log_format)
```

`client_wa = UMFutures()`
`papers = [     ["FUTURES", 'ETHUSDT',1] ]
`   

in array of papers init logging (more string skip):
```
    for cur_paper in papers:
        paper = cur_paper[0]+"."+cur_paper[1]
        ar_log[paper] = pd.DataFrame()
        ar_log[paper].loc[paper,"log"] = logging.getLogger(paper)
        ar_log[paper].loc[paper,"log"].addHandler(console_out)
        ar_log[paper].loc[paper,"log"].setLevel(logging.INFO)
        ar_log[paper].loc[paper,"log"].info(paper +" log script loading...")

```

i view true report:

`2022.07.30 14:39:22.907 : [INFO] : FUTURES.ETHUSDT log script loading...`

if before initializing the logs I call a any function, for example ping

`client_wa.ping()
`

I get duplicate logs, with the second line without formatting.
the error manifests itself in Linux (CentOS, oraclelinux), under Windows there is no such error

    2022.07.30 14:43:36.362 : [INFO] : MAIN log script loading...
    INFO:MAIN:MAIN log script loading...

python ver 3.10.5 (same error in ver 3.6)

**Comment by 2pd** [comment]
Can you write a simple executable gist for us to duplicate?

**Comment by Rilin** [comment]
its hard. please, delete issue
