### ISSUE TITLE
'str' object has no attribute 'query'

### ISSUE THREAD

**Issue by DonyTrumpy** [binance/binance-futures-connector-python#45]
Hi there,

I've been trying to access the binance data for the long-short ratio using your python connector but despite having followed the different steps I still encounter a few struggles:

When doing it via 'binance/um_futures/market.py', I get the following error:

![Capture d’écran (4)](https://user-images.githubusercontent.com/90271989/182192975-6d55d5c9-9cce-48cc-845a-701eca97c82f.png)

Fortunately you provided a second option in your examples, and although I can see the raw data, I am unable to access it:

![Capture d’écran (3)](https://user-images.githubusercontent.com/90271989/182193422-2cf536c4-c9a7-4855-a3e6-7b16cfdd33d2.png)

Any luck you know what is going on for either of them?

Thank you for your time,

A

**Comment by DonyTrumpy** [comment]
From what I understand, it will return just the name of the table, not the table itself. You have to open the table first and then query() on the table.

**Comment by 2pd** [comment]
They are python json object, get values by access the key:


https://github.com/binance/binance-toolbox-python/blob/master/list_break_symbols.py#L17

This is the usage of spot connector, but this futures connector has the same design.
