### ISSUE TITLE
mark_price endpoint doesn't required Symbol argument

### ISSUE THREAD

**Issue by hamedf62** [binance/binance-futures-connector-python#48]
greeting,

according to latest Binance Future Api Docs, premiumIndex endpoint:

GET /fapi/v1/premiumIndex

does not required symbol as mandatory argument, but in the current version its mandatory.

thanks

**Comment by chairz-2** [comment]
Thank you for bringing this up. We will do the necessary fix.

**Comment by chairz-2** [comment]
Fixed in #53
