### ISSUE TITLE
Proxies

### ISSUE THREAD

**Issue by 3o45d** [binance/binance-futures-connector-python#49]
How to use a proxy with authorization? HTTPS/SOCKS?

**Comment by 2pd** [comment]
As `requests` is the http client used in the library, please feel free to refer to here:

https://requests.readthedocs.io/en/latest/user/advanced/#proxies

And see more details of how to setup proxies.

**Comment by 2pd** [comment]
To use https or socks proxy, you may have a try:

```python
http_proxies = { 'https': 'https://username:password@127.0.0.1:3128' }
client = Client(proxies=http_proxies)

socks_proxies = {'https': 'socks5://username:password@127.0.0.1:1080' }
client = Client(proxies=socks_proxies)
```
