### ISSUE TITLE
message_handler no work

### ISSUE THREAD

**Issue by pureloveljc** [binance/binance-futures-connector-python#55]
import time
import logging
from binance.lib.utils import config_logging
from binance.websocket.um_futures.websocket_client import UMFuturesWebsocketClient

config_logging(logging, logging.DEBUG)

def message_handler(message):
    print(message)

my_client = UMFuturesWebsocketClient()
my_client.start()

my_client.kline(
    symbol="btcusdt",
    id=12,
    interval="1d",
    callback=message_handler,
)

time.sleep(10)

logging.debug("closing ws connection")
my_client.stop()

this is oupuit:
INFO:root:Connection with URL: wss://fstream.binance.com/ws
INFO:root:Start to connect....
DEBUG:root:closing ws connection

Process finished with exit code 0
![image](https://user-images.githubusercontent.com/32063794/193718846-3c9345cd-f9f3-46f8-b176-a6d6375fbf46.png)

**Comment by 2pd** [comment]
Can you try if you can connect to WebSocket server by:


```shell
curl -v -o - --http1.1 \
--include \
--no-buffer \
--header "Connection: Upgrade" \
--header "Upgrade: websocket" \
--header "Host: stream.binance.com:9443" \
--header "Origin: https://stream.binance.com:9443" \
--header "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" \
--header "Sec-WebSocket-Version: 13" \
https://stream.binance.com:9443/ws/bnbusdt@ticker

```
