### ISSUE TITLE
mandatory "symbol" in get_account_trades()

### ISSUE THREAD

**Issue by Rilin** [binance/binance-futures-connector-python#58]
i try to run the request but get_account_trades() without "symbol"  - it gives an error

**TypeError: get_account_trades() missing 1 required positional argument: 'symbol'**

Indeed, in the documentation this parameter is mandatory.
But at the same time, postman gives out data.

![image](https://user-images.githubusercontent.com/3840279/198607917-128c4eee-8445-43eb-b64b-eb37eb4a98f6.png)

I need to get trades on symbol, that has not been traded for more than 7 days.
Is there any other possibility to do this?

**Comment by 2pd** [comment]
It's recommended to set symbol for this method.
