### ISSUE TITLE
module 'OpenSSL.SSL' has no attribute 'TLS_METHOD'

### ISSUE THREAD

**Issue by jinni05** [binance/binance-futures-connector-python#59]
Hi, 

When I tried to test websocket um_futures it appear the exception:

Exception has occurred: AttributeError
module 'OpenSSL.SSL' has no attribute 'TLS_METHOD'

Any idea to solve to exception? I follow the readme.md to test

**Comment by 2pd** [comment]
what is your OS? and python version?

**Comment by jinni05** [comment]
Hi, I run on Window 11 + Python 3.9.7

**Comment by dylanwu19850222** [comment]
I have the same problem in Windows.
Then I switch to a Linux OS, the problem didn't exist.

**Comment by 2pd** [comment]
Please have another try of the latest release on Windows.
