### ISSUE TITLE
How to get multiple tickers' kline streams

### ISSUE THREAD

**Issue by SoundProvider** [binance/binance-futures-connector-python#62]
Hello thank you for making this library
I want to know if I can get multiple kline streams.

https://github.com/binance/binance-futures-connector-python/blob/d30576a6d8e6edb706c8b013eb11167b58e9c33a/binance/websocket/websocket_client.py#L38
```python
if self._single_stream(stream):
            stream = [stream]
        else:
            combined = True

        data = {"method": "SUBSCRIBE", "params": stream, "id": id}
```
this line shows that websocket_client can get stream data of multiple tickers

https://github.com/binance/binance-futures-connector-python/blob/d30576a6d8e6edb706c8b013eb11167b58e9c33a/binance/websocket/um_futures/websocket_client.py#L39
```python
def kline(self, symbol: str, id: int, interval: str, callback, **kwargs):
        """Kline/Candlestick Streams
        The Kline/Candlestick Stream push updates to the current klines/candlestick every 250 milliseconds (if existing)
        Stream Name: <symbol>@kline_<interval>
        https://binance-docs.github.io/apidocs/futures/en/#kline-candlestick-streams
        interval:
        m -> minutes; h -> hours; d -> days; w -> weeks; M -> months
        - 1m
        - 3m
        - 5m
        - 15m
        - 30m
        - 1h
        - 2h
        - 4h
        - 6h
        - 8h
        - 12h
        - 1d
        - 3d
        - 1w
        - 1M
        Update Speed: 250ms
        """

        self.live_subscribe(
            "{}@kline_{}".format(symbol.lower(), interval), id, callback, **kwargs
        )

```

but the actual kline method seems to get just single ticker as input

Is there any way to get multiple tickers' kline streams?

**Comment by 2pd** [comment]
Please check this:
https://github.com/binance/binance-futures-connector-python/issues/65#issuecomment-1378358699
