### ISSUE TITLE
Error install pip

### ISSUE THREAD

**Issue by hengkicode** [binance/binance-futures-connector-python#70]
Collecting binance-futures-connector
  Downloading binance_futures_connector-3.3.0-py3-none-any.whl (36 kB)
Collecting autobahn>=21.2.1
  Using cached autobahn-22.12.1.tar.gz (479 kB)
  ERROR: Error [WinError 225] Operation did not complete successfully because the file contains a virus or potentially unwanted software while executing command python setup.py egg_info
  Preparing metadata (setup.py) ... error
ERROR: Could not install packages due to an OSError: [WinError 225] Operation did not complete successfully because the file contains a virus or potentially unwanted software

**Comment by 2pd** [comment]
hmmm, what's your OS and python version?

**Comment by 2pd** [comment]
Please reopen the issue if you need further help.
