### ISSUE TITLE
通过websocket无法获取到价格数据

### ISSUE THREAD

**Issue by waxsnybb** [binance/binance-futures-connector-python#73]
各位好，我使用币安的SDK 想尝试通过websocket获取价格数据，但没有返回任何数据。任何根据技术人员的指导，我尝试通过以下代码确认websocket连接是否好使。运行后10秒，得到closed connection，然后就停止了。
请问各位大佬，该如何解决，谢谢。

运行代码如下所示：
import websocket
import json

testnet = "wss://fstream.binance.com/ws/bnbusdt@bookTicker"

def on_open(ws):
    print('opened connection')
    #ws.send(payload)

def on_close(ws):
    print('closed connection')

def on_message(ws, message):
    json_message = json.loads(message)
    print(json_message)

ws =websocket.WebSocketApp(testnet,on_open=on_open, on_close=on_close, on_message=on_message)
ws.run_forever()

**Comment by 2pd** [comment]
你这个没有用这个库啊？ 用的是websocket的库。  url和代码看起来没问题，我试下可以拿到数据。是不是你的网络链接有问题？

**Comment by waxsnybb** [comment]
> 你这个没有用这个库啊？ 用的是websocket的库。 url和代码看起来没问题，我试下可以拿到数据。是不是你的网络链接有问题？

非常感谢，是我的网络问题，后来我修改了代理总算能获取到数据了。
但还是有个问题，我用币安的SDK WSS订阅频道时，会报SSL error: certificate verify failed，说我SSL验证失败，这个一直没弄好，您知道该如何解决吗。

![图片](https://user-images.githubusercontent.com/55384869/215639821-8922f4ec-0353-4df9-8973-8d943ee8a637.png)

**Comment by 2pd** [comment]
```python
import os, certifi
os.environ['SSL_CERT_FILE'] = certifi.where()
```

试试加上上面代码，Windows的环境有时候拿ssl证书有问题。

**Comment by aisling-2** [comment]
Due to lack of response, we're closing this issue, feel free to reopen if there's following questions.
