### ISSUE TITLE
不能连接websocket，似乎需要设置代理，websocket如何设置代理？

### ISSUE THREAD

**Issue by haisu888** [binance/binance-futures-connector-python#74]
run:
examples\websocket\um_futures\ticker.py' 
INFO:root:Connection with URL: wss://fstream.binance.com/ws
INFO:root:Start to connect....
ERROR:root:Can't connect to server. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.TCPTimedOutError'>: TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
]. Retrying: 1
INFO:root:Start to connect....

**Comment by 2pd** [comment]
不好意思，websocket还不支持代理。 可以试试全局代理？
