### ISSUE TITLE
cannot import modules from the package

### ISSUE THREAD

**Issue by silviumatei** [binance/binance-futures-connector-python#77]
Hello,

This may be really silly but I cannot import anything from this package. 
I made this install into an environment: 
`pip install binance-futures-connector>=3.3.0 autobahn>=21.2.1 Twisted>=22.2.0 requests>=2.25.1 pyOpenSSL>=19.0.0 service-identity>=21.1.0 pycryptodome>=3.15.0`

I have windows 11, conda 22.11.1 and python 3.9.15 installed. 
When I try this` from binance.cm_futures import CMFutures` it says: "ModuleNotFoundError: No module named 'binance.cm_futures'" 

The only thing which does not throw an error is `import binance`. I checked the folders and the package creates the 'binance' folder with these files:
```
__init__.py
__version__.py
api.py
error.py
```

and these folders:
```
__pycache__
cm_futures
lib
um_futures
websocket
```

But then for everything, it tells me there's no module for it. What can be the issue?

**Comment by silviumatei** [comment]
I figured it out. there was some binance package installed in the default conda env creating a binance.py file in the site-packages folder. running a `pip uninstall binance` and then reinstalling the this package did the trick

**Comment by 2pd** [comment]
great, thanks for updates.
