### ISSUE TITLE
Project contribution guidelines

### ISSUE THREAD

**Issue by oktep** [binance/binance-futures-connector-python#79]
What are the guidelines if I want to create pull request and suggest some major / minor  changes in the code base?

How the package is tested? I wasn't able to find any tests.
How fast the approval process is?
What is the branches naming convention?

Thanks
Peter

**Comment by 2pd** [comment]
Hi the project contribution is not ready yet. however it's required to pass the check in the pipeline that should has:
- black check
- flake8 check
- each endpoint should include an example file.

**Comment by oktep** [comment]
Great I think mention even just this three bullet points as dev-guide (in README.md) for now will be great (I don't know how many people are reading issues.).

My next questions are:
Is there any a priory requirements create Issue before Pull Request, or just PR with description is sufficient?
If yes (to previous question) Is necessary to create new issue in case of code base improvement PR?

**Comment by 2pd** [comment]
If the description is clear enough for the PR, that should be helpful for the review.
