### ISSUE TITLE
transfer(futures balance to spot) 

### ISSUE THREAD

**Issue by NikolayNelubov** [binance/binance-futures-connector-python#85]
Hello. Thank you very much for your work. I have a question --> is it possible to transfer money with the help of this library both from a spot account to a futures account in both directions(Binance API --> POST /sapi/v1/asset/transfer)?  If not, are there any plans to add such functionality? Thank you.

**Comment by 2pd** [comment]
this endpoint is available in this library:

https://github.com/binance/binance-connector-python

**Comment by NikolayNelubov** [comment]
Thanks for the answer. I work only with futures, I would not like to install another library for the sake of one function. It seems to me that it would be right to place it in this library. After all, futures balance management is very important.
