### ISSUE TITLE
[Recent accounts] Unable to connect to testnet

### ISSUE THREAD

**Issue by altmdb** [binance/binance-futures-connector-python#88]
Hi all, 

I am trying to connect to my futures testnet account. I have followed the instructions from [here](https://www.binance.com/en/support/faq/how-to-test-my-functions-on-binance-testnet-ab78f9a1b8824cf0a106b4229c76496d). I have copied my API key and secret key, as below:
![image](https://user-images.githubusercontent.com/128263446/226144687-f3d36901-da26-416e-84db-f00574391db0.png)

To test out the connection, I run this minimal python code

```python
from binance.cm_futures import CMFutures

cm_futures_client = CMFutures(key=..., secret=..., base_url="https://testnet.binancefuture.com")

print(cm_futures_client.account())
```

But this systematically fails, with the following error (changed IP).
```
binance.error.ClientError: (401, -2015, 'Invalid API-key, IP, or permissions for action, request ip: 1.2.3.4', {'Content-Type': 'application/json', 'Content-Length': '96', 'Connection': 'keep-alive', 'Date': 'Sat, 18 Mar 2023 23:04:03 GMT', 'Server': 'Bengine', 'X-MBX-USED-WEIGHT-1M': '5', 'x-response-time': '1ms', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 7dd34c129f9f4ea3b51fe1fa61080774.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'YUL62-C2', 'X-Amz-Cf-Id': 'TOMtbfKoR1wfofOzSxiiTBWdWXu7UPBnhHI_It0P_eWj8ZLqxcudYw=='})
```

Could someone please assist? Thanks a lot!
Note: My test account says "regular user - unverified". Also note that I have not created a test spot API key, as I understand this is different.

**Comment by jonte-z** [comment]
Hi there,

I just tested for myself and it's working fine. I also tested by copying your code exactly and running that and it's working:
![image](https://user-images.githubusercontent.com/114036008/226498858-15f5aaff-41b7-4bbb-a950-1d8d6eecb607.png)

FYI my testnet account also says "Regular User - Unverified".
Out of interest, could you try creating a new testnet account and trying again with the newly generated API Key + Secret and see if you get the same error?

Regards,

**Comment by paljaske** [comment]
I have the same error. Already made 2 accounts. Same error with different api keys. My code is fine. It works with a testnet account from a friend. So i guess there is something wrong with new testnet accounts ?
Code also works on my main account.

**Comment by denqxotl** [comment]
I'm facing the same problem. Just created an account today.

**Comment by sheff3rd** [comment]
Facing the same issue. Just created an testnet account and unable to connect

**Comment by 2pd** [comment]
It could be the issue from the testnet, but an issue from the library. Please open issue again if it happens next time.
