### ISSUE TITLE
Websocket api. Automatic reconnection.

### ISSUE THREAD

**Issue by deployRama** [binance/binance-futures-connector-python#90]
As it says in the documentation, Binance does not guarantee that a websocket will stay connected for more than 24 hours.

I wanted to ask you if python-connector is able to detect when binance disconnects the websocket and automatically reconnect it. In case it doesn't have that ability, do you have any ideas to how i can develop it?

**Comment by 2pd** [comment]
Yes, the connector can auto reconnect a few times.

**Comment by SoundProvider** [comment]
> Yes, the connector can auto reconnect a few times.

@2pd
Could you please comment the code line where the connector does reconnection? Thanks
