### ISSUE TITLE
Signature For request is not valid 

### ISSUE THREAD

**Issue by frank-sassy** [binance/binance-futures-connector-python#94]
I am trying to create a test order and keep getting this , even on the example codes provided in the repo
my system configuration : python 3.9 , mac m1 

![image_2023-04-24_15-59-28](https://user-images.githubusercontent.com/130788755/233973484-c2473840-1f52-473a-91b3-f6a52c805cf9.png)

**Comment by 2pd** [comment]
did you provide the futures testnet API and secret for the script?

**Comment by aisling-2** [comment]
Due to lack of response, we're closing this issue. Feel free to re-open if question persists.
