### ISSUE TITLE
Include Modify Order for UMFutures

### ISSUE THREAD

**Issue by rahulpoptani** [binance/binance-futures-connector-python#99]
Modify Order endpoint is now available for Futures: https://binance-docs.github.io/apidocs/futures/en/#modify-order-trade

**Comment by 2pd** [comment]
thanks, we will add it soon.

**Comment by SquareGraph** [comment]
Hey guys, need some help with this? Or possible ETA? I started to implement Your lib into my project, but this endpoint is crucial for me.
